name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: run test
      run: |
        clang++ -std=c++17 test.cpp  -lgtest -lgtest_main -lpthread
        ./a.out
